// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileManager.proto

#ifndef PROTOBUF_INCLUDED_FileManager_2eproto
#define PROTOBUF_INCLUDED_FileManager_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_FileManager_2eproto 

namespace protobuf_FileManager_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_FileManager_2eproto
class DirInfo;
class DirInfoDefaultTypeInternal;
extern DirInfoDefaultTypeInternal _DirInfo_default_instance_;
class DirRet;
class DirRetDefaultTypeInternal;
extern DirRetDefaultTypeInternal _DirRet_default_instance_;
namespace google {
namespace protobuf {
template<> ::DirInfo* Arena::CreateMaybeMessage<::DirInfo>(Arena*);
template<> ::DirRet* Arena::CreateMaybeMessage<::DirRet>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class DirInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DirInfo) */ {
 public:
  DirInfo();
  virtual ~DirInfo();

  DirInfo(const DirInfo& from);

  inline DirInfo& operator=(const DirInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DirInfo(DirInfo&& from) noexcept
    : DirInfo() {
    *this = ::std::move(from);
  }

  inline DirInfo& operator=(DirInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DirInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DirInfo* internal_default_instance() {
    return reinterpret_cast<const DirInfo*>(
               &_DirInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DirInfo* other);
  friend void swap(DirInfo& a, DirInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DirInfo* New() const final {
    return CreateMaybeMessage<DirInfo>(NULL);
  }

  DirInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DirInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DirInfo& from);
  void MergeFrom(const DirInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DirInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string uuid = 3;
  void clear_uuid();
  static const int kUuidFieldNumber = 3;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  #if LANG_CXX11
  void set_uuid(::std::string&& value);
  #endif
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // int64 dirid = 1;
  void clear_dirid();
  static const int kDiridFieldNumber = 1;
  ::google::protobuf::int64 dirid() const;
  void set_dirid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:DirInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  ::google::protobuf::int64 dirid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_FileManager_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DirRet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DirRet) */ {
 public:
  DirRet();
  virtual ~DirRet();

  DirRet(const DirRet& from);

  inline DirRet& operator=(const DirRet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DirRet(DirRet&& from) noexcept
    : DirRet() {
    *this = ::std::move(from);
  }

  inline DirRet& operator=(DirRet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DirRet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DirRet* internal_default_instance() {
    return reinterpret_cast<const DirRet*>(
               &_DirRet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(DirRet* other);
  friend void swap(DirRet& a, DirRet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DirRet* New() const final {
    return CreateMaybeMessage<DirRet>(NULL);
  }

  DirRet* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DirRet>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DirRet& from);
  void MergeFrom(const DirRet& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DirRet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string jsoninfo = 2;
  void clear_jsoninfo();
  static const int kJsoninfoFieldNumber = 2;
  const ::std::string& jsoninfo() const;
  void set_jsoninfo(const ::std::string& value);
  #if LANG_CXX11
  void set_jsoninfo(::std::string&& value);
  #endif
  void set_jsoninfo(const char* value);
  void set_jsoninfo(const char* value, size_t size);
  ::std::string* mutable_jsoninfo();
  ::std::string* release_jsoninfo();
  void set_allocated_jsoninfo(::std::string* jsoninfo);

  // int32 code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DirRet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr jsoninfo_;
  ::google::protobuf::int32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_FileManager_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DirInfo

// int64 dirid = 1;
inline void DirInfo::clear_dirid() {
  dirid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 DirInfo::dirid() const {
  // @@protoc_insertion_point(field_get:DirInfo.dirid)
  return dirid_;
}
inline void DirInfo::set_dirid(::google::protobuf::int64 value) {
  
  dirid_ = value;
  // @@protoc_insertion_point(field_set:DirInfo.dirid)
}

// string name = 2;
inline void DirInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DirInfo::name() const {
  // @@protoc_insertion_point(field_get:DirInfo.name)
  return name_.GetNoArena();
}
inline void DirInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DirInfo.name)
}
#if LANG_CXX11
inline void DirInfo::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DirInfo.name)
}
#endif
inline void DirInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DirInfo.name)
}
inline void DirInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DirInfo.name)
}
inline ::std::string* DirInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:DirInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DirInfo::release_name() {
  // @@protoc_insertion_point(field_release:DirInfo.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DirInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:DirInfo.name)
}

// string uuid = 3;
inline void DirInfo::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DirInfo::uuid() const {
  // @@protoc_insertion_point(field_get:DirInfo.uuid)
  return uuid_.GetNoArena();
}
inline void DirInfo::set_uuid(const ::std::string& value) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DirInfo.uuid)
}
#if LANG_CXX11
inline void DirInfo::set_uuid(::std::string&& value) {
  
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DirInfo.uuid)
}
#endif
inline void DirInfo::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DirInfo.uuid)
}
inline void DirInfo::set_uuid(const char* value, size_t size) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DirInfo.uuid)
}
inline ::std::string* DirInfo::mutable_uuid() {
  
  // @@protoc_insertion_point(field_mutable:DirInfo.uuid)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DirInfo::release_uuid() {
  // @@protoc_insertion_point(field_release:DirInfo.uuid)
  
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DirInfo::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    
  } else {
    
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:DirInfo.uuid)
}

// -------------------------------------------------------------------

// DirRet

// int32 code = 1;
inline void DirRet::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 DirRet::code() const {
  // @@protoc_insertion_point(field_get:DirRet.code)
  return code_;
}
inline void DirRet::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:DirRet.code)
}

// string jsoninfo = 2;
inline void DirRet::clear_jsoninfo() {
  jsoninfo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DirRet::jsoninfo() const {
  // @@protoc_insertion_point(field_get:DirRet.jsoninfo)
  return jsoninfo_.GetNoArena();
}
inline void DirRet::set_jsoninfo(const ::std::string& value) {
  
  jsoninfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DirRet.jsoninfo)
}
#if LANG_CXX11
inline void DirRet::set_jsoninfo(::std::string&& value) {
  
  jsoninfo_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DirRet.jsoninfo)
}
#endif
inline void DirRet::set_jsoninfo(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  jsoninfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DirRet.jsoninfo)
}
inline void DirRet::set_jsoninfo(const char* value, size_t size) {
  
  jsoninfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DirRet.jsoninfo)
}
inline ::std::string* DirRet::mutable_jsoninfo() {
  
  // @@protoc_insertion_point(field_mutable:DirRet.jsoninfo)
  return jsoninfo_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DirRet::release_jsoninfo() {
  // @@protoc_insertion_point(field_release:DirRet.jsoninfo)
  
  return jsoninfo_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DirRet::set_allocated_jsoninfo(::std::string* jsoninfo) {
  if (jsoninfo != NULL) {
    
  } else {
    
  }
  jsoninfo_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), jsoninfo);
  // @@protoc_insertion_point(field_set_allocated:DirRet.jsoninfo)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_FileManager_2eproto
