#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "FileManager.pb.h"

namespace DirAddService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void DirAdd(DirInfo *request, DirRet *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using DirAddDone = std::function<void (DirRet *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void DirAdd(const DirInfo *req, DirAddDone done);
	void DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirAdd(const DirInfo *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_DirAdd_task(DirAddDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void DirAdd(const DirInfo *req, DirAddDone done);
	void DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirAdd(const DirInfo *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_DirAdd_task(DirAddDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void DirAdd(const DirInfo *req, DirAddDone done);
	void DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirAdd(const DirInfo *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_DirAdd_task(DirAddDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void DirAdd(const DirInfo *req, DirAddDone done);
	void DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirAdd(const DirInfo *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_DirAdd_task(DirAddDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void DirAdd(const DirInfo *req, DirAddDone done);
	void DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirAdd(const DirInfo *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_DirAdd_task(DirAddDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("DirAddService")
{
	this->srpc::RPCService::add_method("DirAdd",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::DirAdd);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("DirAddService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("DirAddService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::DirAdd(const DirInfo *req, DirAddDone done)
{
	auto *task = this->create_rpc_client_task("DirAdd", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirAdd(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> SRPCClient::async_DirAdd(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirAdd", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_DirAdd_task(DirAddDone done)
{
	return this->create_rpc_client_task("DirAdd", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("DirAddService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("DirAddService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::DirAdd(const DirInfo *req, DirAddDone done)
{
	auto *task = this->create_rpc_client_task("DirAdd", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirAdd(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> SRPCHttpClient::async_DirAdd(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirAdd", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_DirAdd_task(DirAddDone done)
{
	return this->create_rpc_client_task("DirAdd", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("DirAddService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("DirAddService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::DirAdd(const DirInfo *req, DirAddDone done)
{
	auto *task = this->create_rpc_client_task("DirAdd", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirAdd(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> BRPCClient::async_DirAdd(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirAdd", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_DirAdd_task(DirAddDone done)
{
	return this->create_rpc_client_task("DirAdd", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("DirAddService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("DirAddService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::DirAdd(const DirInfo *req, DirAddDone done)
{
	auto *task = this->create_rpc_client_task("/DirAddService/DirAdd", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirAdd(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> TRPCClient::async_DirAdd(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("/DirAddService/DirAdd", srpc::RPCAsyncFutureCallback<DirRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_DirAdd_task(DirAddDone done)
{
	auto *task = this->create_rpc_client_task("/DirAddService/DirAdd", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("DirAddService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("DirAddService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::DirAdd(const DirInfo *req, DirAddDone done)
{
	auto *task = this->create_rpc_client_task("DirAdd", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::DirAdd(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirAdd(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> TRPCHttpClient::async_DirAdd(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirAdd", srpc::RPCAsyncFutureCallback<DirRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_DirAdd_task(DirAddDone done)
{
	auto *task = this->create_rpc_client_task("DirAdd", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace DirAddService


namespace DirRmService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void DirRm(DirInfo *request, DirRet *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using DirRmDone = std::function<void (DirRet *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void DirRm(const DirInfo *req, DirRmDone done);
	void DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirRm(const DirInfo *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_DirRm_task(DirRmDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void DirRm(const DirInfo *req, DirRmDone done);
	void DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirRm(const DirInfo *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_DirRm_task(DirRmDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void DirRm(const DirInfo *req, DirRmDone done);
	void DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirRm(const DirInfo *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_DirRm_task(DirRmDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void DirRm(const DirInfo *req, DirRmDone done);
	void DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirRm(const DirInfo *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_DirRm_task(DirRmDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void DirRm(const DirInfo *req, DirRmDone done);
	void DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirRm(const DirInfo *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_DirRm_task(DirRmDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("DirRmService")
{
	this->srpc::RPCService::add_method("DirRm",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::DirRm);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("DirRmService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("DirRmService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::DirRm(const DirInfo *req, DirRmDone done)
{
	auto *task = this->create_rpc_client_task("DirRm", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirRm(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> SRPCClient::async_DirRm(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirRm", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_DirRm_task(DirRmDone done)
{
	return this->create_rpc_client_task("DirRm", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("DirRmService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("DirRmService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::DirRm(const DirInfo *req, DirRmDone done)
{
	auto *task = this->create_rpc_client_task("DirRm", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirRm(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> SRPCHttpClient::async_DirRm(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirRm", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_DirRm_task(DirRmDone done)
{
	return this->create_rpc_client_task("DirRm", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("DirRmService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("DirRmService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::DirRm(const DirInfo *req, DirRmDone done)
{
	auto *task = this->create_rpc_client_task("DirRm", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirRm(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> BRPCClient::async_DirRm(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirRm", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_DirRm_task(DirRmDone done)
{
	return this->create_rpc_client_task("DirRm", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("DirRmService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("DirRmService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::DirRm(const DirInfo *req, DirRmDone done)
{
	auto *task = this->create_rpc_client_task("/DirRmService/DirRm", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirRm(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> TRPCClient::async_DirRm(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("/DirRmService/DirRm", srpc::RPCAsyncFutureCallback<DirRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_DirRm_task(DirRmDone done)
{
	auto *task = this->create_rpc_client_task("/DirRmService/DirRm", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("DirRmService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("DirRmService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::DirRm(const DirInfo *req, DirRmDone done)
{
	auto *task = this->create_rpc_client_task("DirRm", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::DirRm(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirRm(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> TRPCHttpClient::async_DirRm(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirRm", srpc::RPCAsyncFutureCallback<DirRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_DirRm_task(DirRmDone done)
{
	auto *task = this->create_rpc_client_task("DirRm", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace DirRmService


namespace DirQueryService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void DirQuery(DirInfo *request, DirRet *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using DirQueryDone = std::function<void (DirRet *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void DirQuery(const DirInfo *req, DirQueryDone done);
	void DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirQuery(const DirInfo *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_DirQuery_task(DirQueryDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void DirQuery(const DirInfo *req, DirQueryDone done);
	void DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirQuery(const DirInfo *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_DirQuery_task(DirQueryDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void DirQuery(const DirInfo *req, DirQueryDone done);
	void DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirQuery(const DirInfo *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_DirQuery_task(DirQueryDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void DirQuery(const DirInfo *req, DirQueryDone done);
	void DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirQuery(const DirInfo *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_DirQuery_task(DirQueryDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void DirQuery(const DirInfo *req, DirQueryDone done);
	void DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> async_DirQuery(const DirInfo *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_DirQuery_task(DirQueryDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("DirQueryService")
{
	this->srpc::RPCService::add_method("DirQuery",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::DirQuery);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("DirQueryService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("DirQueryService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::DirQuery(const DirInfo *req, DirQueryDone done)
{
	auto *task = this->create_rpc_client_task("DirQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> SRPCClient::async_DirQuery(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirQuery", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_DirQuery_task(DirQueryDone done)
{
	return this->create_rpc_client_task("DirQuery", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("DirQueryService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("DirQueryService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::DirQuery(const DirInfo *req, DirQueryDone done)
{
	auto *task = this->create_rpc_client_task("DirQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> SRPCHttpClient::async_DirQuery(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirQuery", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_DirQuery_task(DirQueryDone done)
{
	return this->create_rpc_client_task("DirQuery", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("DirQueryService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("DirQueryService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::DirQuery(const DirInfo *req, DirQueryDone done)
{
	auto *task = this->create_rpc_client_task("DirQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> BRPCClient::async_DirQuery(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirQuery", srpc::RPCAsyncFutureCallback<DirRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_DirQuery_task(DirQueryDone done)
{
	return this->create_rpc_client_task("DirQuery", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("DirQueryService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("DirQueryService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::DirQuery(const DirInfo *req, DirQueryDone done)
{
	auto *task = this->create_rpc_client_task("/DirQueryService/DirQuery", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> TRPCClient::async_DirQuery(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("/DirQueryService/DirQuery", srpc::RPCAsyncFutureCallback<DirRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_DirQuery_task(DirQueryDone done)
{
	auto *task = this->create_rpc_client_task("/DirQueryService/DirQuery", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("DirQueryService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("DirQueryService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::DirQuery(const DirInfo *req, DirQueryDone done)
{
	auto *task = this->create_rpc_client_task("DirQuery", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::DirQuery(const DirInfo *req, DirRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DirQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<DirRet, srpc::RPCSyncContext>> TRPCHttpClient::async_DirQuery(const DirInfo *req)
{
	using RESULT = std::pair<DirRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<DirRet>("DirQuery", srpc::RPCAsyncFutureCallback<DirRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_DirQuery_task(DirQueryDone done)
{
	auto *task = this->create_rpc_client_task("DirQuery", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace DirQueryService

