#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "UserSign.pb.h"

namespace UserSignUpService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void SignUp(UserSign *request, UserRet *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using SignUpDone = std::function<void (UserRet *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void SignUp(const UserSign *req, SignUpDone done);
	void SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignUp(const UserSign *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_SignUp_task(SignUpDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void SignUp(const UserSign *req, SignUpDone done);
	void SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignUp(const UserSign *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_SignUp_task(SignUpDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void SignUp(const UserSign *req, SignUpDone done);
	void SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignUp(const UserSign *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_SignUp_task(SignUpDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void SignUp(const UserSign *req, SignUpDone done);
	void SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignUp(const UserSign *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_SignUp_task(SignUpDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void SignUp(const UserSign *req, SignUpDone done);
	void SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignUp(const UserSign *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_SignUp_task(SignUpDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("UserSignUpService")
{
	this->srpc::RPCService::add_method("SignUp",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::SignUp);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("UserSignUpService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("UserSignUpService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::SignUp(const UserSign *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> SRPCClient::async_SignUp(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("SignUp", srpc::RPCAsyncFutureCallback<UserRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_SignUp_task(SignUpDone done)
{
	return this->create_rpc_client_task("SignUp", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("UserSignUpService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("UserSignUpService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::SignUp(const UserSign *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> SRPCHttpClient::async_SignUp(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("SignUp", srpc::RPCAsyncFutureCallback<UserRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_SignUp_task(SignUpDone done)
{
	return this->create_rpc_client_task("SignUp", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("UserSignUpService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("UserSignUpService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::SignUp(const UserSign *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> BRPCClient::async_SignUp(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("SignUp", srpc::RPCAsyncFutureCallback<UserRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_SignUp_task(SignUpDone done)
{
	return this->create_rpc_client_task("SignUp", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("UserSignUpService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("UserSignUpService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::SignUp(const UserSign *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("/UserSignUpService/SignUp", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> TRPCClient::async_SignUp(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("/UserSignUpService/SignUp", srpc::RPCAsyncFutureCallback<UserRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_SignUp_task(SignUpDone done)
{
	auto *task = this->create_rpc_client_task("/UserSignUpService/SignUp", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("UserSignUpService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("UserSignUpService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::SignUp(const UserSign *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::SignUp(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> TRPCHttpClient::async_SignUp(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("SignUp", srpc::RPCAsyncFutureCallback<UserRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_SignUp_task(SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace UserSignUpService


namespace UserSignInService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void SignIn(UserSign *request, UserRet *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using SignInDone = std::function<void (UserRet *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void SignIn(const UserSign *req, SignInDone done);
	void SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignIn(const UserSign *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_SignIn_task(SignInDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void SignIn(const UserSign *req, SignInDone done);
	void SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignIn(const UserSign *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_SignIn_task(SignInDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void SignIn(const UserSign *req, SignInDone done);
	void SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignIn(const UserSign *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_SignIn_task(SignInDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void SignIn(const UserSign *req, SignInDone done);
	void SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignIn(const UserSign *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_SignIn_task(SignInDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void SignIn(const UserSign *req, SignInDone done);
	void SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> async_SignIn(const UserSign *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_SignIn_task(SignInDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("UserSignInService")
{
	this->srpc::RPCService::add_method("SignIn",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::SignIn);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("UserSignInService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("UserSignInService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::SignIn(const UserSign *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> SRPCClient::async_SignIn(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("SignIn", srpc::RPCAsyncFutureCallback<UserRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_SignIn_task(SignInDone done)
{
	return this->create_rpc_client_task("SignIn", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("UserSignInService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("UserSignInService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::SignIn(const UserSign *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> SRPCHttpClient::async_SignIn(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("SignIn", srpc::RPCAsyncFutureCallback<UserRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_SignIn_task(SignInDone done)
{
	return this->create_rpc_client_task("SignIn", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("UserSignInService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("UserSignInService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::SignIn(const UserSign *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> BRPCClient::async_SignIn(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("SignIn", srpc::RPCAsyncFutureCallback<UserRet>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_SignIn_task(SignInDone done)
{
	return this->create_rpc_client_task("SignIn", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("UserSignInService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("UserSignInService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::SignIn(const UserSign *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("/UserSignInService/SignIn", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> TRPCClient::async_SignIn(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("/UserSignInService/SignIn", srpc::RPCAsyncFutureCallback<UserRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_SignIn_task(SignInDone done)
{
	auto *task = this->create_rpc_client_task("/UserSignInService/SignIn", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("UserSignInService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("UserSignInService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::SignIn(const UserSign *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::SignIn(const UserSign *req, UserRet *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserRet, srpc::RPCSyncContext>> TRPCHttpClient::async_SignIn(const UserSign *req)
{
	using RESULT = std::pair<UserRet, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserRet>("SignIn", srpc::RPCAsyncFutureCallback<UserRet>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_SignIn_task(SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace UserSignInService

